services:
  dataset:
    image: kakaxi314/dataset
#    image: xpp/neat
    shm_size: '256gb'
    stdin_open: true
    tty: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["bash", "-l"]
#    ports:
#      - 6006:6006
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all


#    environment:
#      - DISPLAY=${DISPLAY}
#      - XAUTHORITY=/root/.Xauthority  # Tell the container where to look
#      - QT_X11_NO_MITSHM=1

    volumes:
       - ./:/root/dataset
       - /media2/dataset/DDAD:/root/dataset/datas/DDAD
       - /media2/dataset/DDAD_streaming:/root/dataset/datas/DDAD_streaming
       - /media2/dataset/BlendedMVS:/root/dataset/datas/BlendedMVS
       - /media2/dataset/BlendedMVS_streaming:/root/dataset/datas/BlendedMVS_streaming
       - /media2/dataset/tartanair_data:/root/dataset/datas/tartanair_data
       - /media2/dataset/tartanair_streaming:/root/dataset/datas/tartanair_streaming
       - /media2/dataset/matterport:/root/dataset/datas/matterport
       - pip_cache:/root/.cache/pip

    working_dir: /root/dataset

volumes:
  pip_cache:

