services:
  dataset:
    image: kakaxi314/tsdf
#    image: xpp/neat
    shm_size: '256gb'
    stdin_open: true
    tty: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["bash", "-l"]
#    ports:
#      - 6006:6006
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all


#    environment:
#      - DISPLAY=${DISPLAY}
#      - XAUTHORITY=/root/.Xauthority  # Tell the container where to look
#      - QT_X11_NO_MITSHM=1

    volumes:
       - ./:/root/dataset
       - /mnt/data/:/root/dataset/datas/


    working_dir: /root/dataset

volumes:
  pip_cache:

