services:
  dataset:
    image: kakaxi314/tsdf
#    image: xpp/neat
    shm_size: '256gb'
    stdin_open: true
    tty: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["bash", "-l"]
#    ports:
#      - 6006:6006
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONPATH=/root/dgp:$PYTHONPATH

#    environment:
#      - DISPLAY=${DISPLAY}
#      - XAUTHORITY=/root/.Xauthority  # Tell the container where to look
#      - QT_X11_NO_MITSHM=1

    volumes:
       - ./:/root/DATASET
       - /run/media/wsl/SANDISK ELE/dataset/:/media/wsl/SANDISK ELE/dataset/
       - /run/media/wsl/SANDISK ELE/dgp-master:/root/dgp
       - pip_cache:/root/.cache/pip

    working_dir: /root/DATASET

volumes:
  pip_cache:

